<?php

namespace app\modules\api\models;

use Yii;

/**
 * This is the model class for table "random".
 *
 * @property int $id
 * @property int $rand
 */
class Random extends \yii\db\ActiveRecord
{
    const SCENARIO_GENERATE = 'generate';

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'random';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['rand'], 'required'],
            [['rand'], 'integer'],
        ];
    }

    public function scenarios()
    {
        $scenarios =  parent::scenarios(); // TODO: Change the autogenerated stub
        $scenarios[self::SCENARIO_GENERATE] = ['rand'];
        return $scenarios;
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'rand' => 'Rand',
        ];
    }
}
